// Flat config generated by @nuxt/eslint from the project (`.nuxt/eslint.config.mjs`), stylistic rules on, plus
// ESLint's size rules at their default limits: complexity 20, nesting depth 4, parameters 3.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    'complexity': 'error',
    'max-depth': 'error',
    'max-params': 'error',
  },
})
