"""`Idempotency-Key` on creations: a retry with the same key replays the same response.

Keys and responses are stored in the database (`IDEMPOTENCY_TTL_S`), so any replica can replay them. The
same key with a different body gets a 422. When two requests race with the same key, the unique constraint
decides and the second one replays the first one's response.
"""

import hashlib
import json
from collections.abc import Awaitable, Callable
from datetime import datetime, timedelta
from typing import Annotated, Any

from fastapi import Header
from fastapi.responses import JSONResponse
from sqlalchemy import delete, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.db import IdempotencyKey, sessionmaker, utcnow
from app.errors import problem

KeyHeader = Annotated[
    str,
    Header(
        alias="Idempotency-Key",
        min_length=8,
        max_length=200,
        description="Unique key per operation, generated by the client (a UUID) and sent unchanged on "
        "every retry.",
    ),
]


def _hash(payload: Any) -> str:
    return hashlib.sha256(json.dumps(payload, sort_keys=True, default=str).encode()).hexdigest()


async def run(
    session: AsyncSession,
    key: str,
    payload: Any,
    create: Callable[[], Awaitable[tuple[int, Any]]],
) -> JSONResponse:
    """`create` performs the operation and returns (status, body); it runs at most once per key."""
    request_hash = _hash(payload)
    stored = await session.scalar(select(IdempotencyKey).where(IdempotencyKey.key == key))
    if stored is not None and stored.created_at < _expiry():
        await session.delete(stored)  # expired, not purged yet: the key is free again
        await session.flush()
        stored = None
    if stored is None:
        status, body = await create()
        stored_body = json.dumps(body)
        session.add(IdempotencyKey(key=key, request_hash=request_hash, status_code=status, body=stored_body))
        try:
            await session.commit()
            return JSONResponse(body, status_code=status)
        except IntegrityError:
            await session.rollback()
            stored = await session.scalar(select(IdempotencyKey).where(IdempotencyKey.key == key))
            if stored is None:
                raise
    if stored.request_hash != request_hash:
        return problem(422, "this idempotency key was already used for a different request")
    replayed = {"Idempotent-Replayed": "true"}
    return JSONResponse(json.loads(stored.body), status_code=stored.status_code, headers=replayed)


def _expiry() -> datetime:
    return utcnow() - timedelta(seconds=get_settings().idempotency_ttl_s)


async def purge() -> int:
    """Deletes expired keys; returns how many."""
    async with sessionmaker()() as session:
        result = await session.execute(delete(IdempotencyKey).where(IdempotencyKey.created_at < _expiry()))
        await session.commit()
        return int(getattr(result, "rowcount", 0) or 0)
